### ISSUE TITLE
config.py

### ISSUE THREAD

**Issue by masnn** [water-lift/SiGNAL#1]
Please use `config.sample.py` instead of `config.py` and DO NOT expose any information..

**Comment by water-lift** [comment]
qwq忘了------------------ 原始邮件 ------------------
发件人: "undefined"<notifications@github.com>
发送时间: 2020年3月26日(星期四) 上午8:25
收件人: "water-lift/SiGNAL"<SiGNAL@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [water-lift/SiGNAL] config.py (#1)




 
Please use config.sample.py instead of config.py and DO NOT expose any information..
 
&mdash;

**Comment by masnn** [comment]
https://help.github.com/cn/github/authenticating-to-github/removing-sensitive-data-from-a-repository
